linters-settings:
  golint:
    min-confidence: 0

  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - typecheck
    - goimports
    - misspell
    - govet
    - revive
    - ineffassign
    - gosimple
    - deadcode
    - unparam
    - unused
    - structcheck

service:
  golangci-lint-version: 1.27.0 # use the fixed version to not introduce new linters unexpectedly

issues:
  exclude-use-default: false
  exclude:
      - should have a package comment
      # TODO(y4m4): Remove once all exported ident. have comments!      
      - comment on exported function
      - comment on exported type
      - should have comment
      - use leading k in Go names
      - comment on exported const
run:
  skip-dirs:
    - pkg/clientgen
