name: "React Code Has No Warnings"
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./portal-ui
        run: yarn
      - name: Check for Warnings in build output
        working-directory: ./portal-ui
        continue-on-error: false
        run: |
          if yarn build | grep "Compiled with warnings"; then echo "There are warnings in the code" && exit 1 ; fi
